### ISSUE TITLE
Correct asset paths in compiled CSS

### ISSUE THREAD

**Issue by whoisgina** [portland-dsa/website-hugo#3]
Asset paths used in the SCSS compile to a path beginning with `/src`. How can we provide a path that Hugo likes? I think that the right spot is in `/static` and that we can handle this with Webpack configuration. What do you think, @egardner?

**Comment by egardner** [comment]
Fixed via #6. The basic idea for future reference is that:

1. Webpack compiles files from `/src` => `/static`
2. Hugo watches `/static` for changes in dev mode
3. When hugo builds, files in `/static` get copied to `/public/assets`

The webpack config file now supports this basic workflow.
